language: python
python:
  - "2.7"
#  - "3.3"
# command to install dependencies
before_install:
  - git clone -b iterative_uniquify https://github.com/clemux/firewoes.git ../firewoes
  - pip install -e ../firewoes
  - sudo apt-get update
  - sudo apt-get install -qq cppcheck lintian npm
  - sudo apt-get install -qq libdom4j-java junit4 libasm3-java libjaxen-java libcommons-lang-java libjdepend-java libjcip-annotations-java java-wrappers libjsr305-java
  - wget ftp://ftp.debian.org/debian/pool/main/f/findbugs-bcel/libfindbugs-bcel-java_6.0~rc3-1_all.deb
  - wget ftp://ftp.debian.org/debian/pool/main/j/jformatstring/libjformatstring-java_0.10~20131207-1_amd64.deb
  - wget ftp://ftp.debian.org/debian/pool/main/f/findbugs/findbugs_2.0.3+repack-1_all.deb
  - sudo dpkg -i libfindbugs-bcel-java_6.0~rc3-1_all.deb libjformatstring-java_0.10~20131207-1_amd64.deb findbugs_2.0.3+repack-1_all.deb
  - travis_retry npm install -g jshint
  - jshint -v
  - gem install roodi
install:
  - pip install -r requirements.txt
  - pip install -r requirements-slave.txt
  - pip install -r requirements-master.txt
  - pip install coveralls
  - pip install flake8
env:
  - DATABASE_URI='postgres://postgres:@localhost:5432/debile_tests'
before_script:
  - flake8 --version
  - psql -c 'create database debile_tests;' -U postgres

# command to run tests
script:
 - coverage run --source=. $(which nosetests)
 - python setup.py test
# flake8
# warnings ignored:
# * E241 (multiple spaces after ':', ',') -> we want to align stuff
 - flake8 debile/ --ignore E711,E241 --max-line-length=200
after_success:
 - coveralls

notifications:
  irc:
    channels:
      - "irc.debian.org#debile"
    on_success: always
    on_failure: always
    skip_join: true
    template:
      - "%{result}: %{repository}#%{build_number} (%{branch} - %{commit}: %{build_url}"
